default_stages: [ push ]
repos:
  - repo: local
    hooks:
      - id: format
        name: Format
        stages: [ commit, push ]
        language: system
        entry: make format
        types: [ python ]
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.2.3
    hooks:
      - id: nbqa-black
        stages: [ commit ]
        files: notebooks
        args: [ --line-length=120, --target-version=py39,]
      - id: nbqa-isort
        stages: [ commit ]
        files: notebooks
        args: [ --profile=black, --project=recommend ]
        

